name: RUN_E2E_TESTS_DOTNET3_LCON
on:
  workflow_dispatch:

permissions:
  id-token: write

env:
  AZURE_FUNCTIONAPP_NAME: FunctionAppDeployment2
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './FunctionApps/Azure functions'
  DOTNET_VERSION: '8.0.x'

jobs:
  run:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: E2E Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: E2E Resolve Project Dependencies Using Dotnet
      shell: pwsh
      run: |
        pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        echo "$env:GITHUB_SHA" > ./output/sha.txt
        popd

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: E2E Run Azure Functions Action
      uses: ./.github/workflows/BuildAndDeployFA.yml
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

    - name: E2E Check HttpTrigger Result
      shell: pwsh
      run: |
        $i = 0
        while ($i -lt 10) {
          sleep 10
          $RESPONSE = $(curl "${{ steps.fa.outputs.app-url }}/api/FunctionTest")
          $RESULT = ($RESPONSE -eq "$env:GITHUB_SHA")
          if ($RESULT) {
            exit 0
          }
          $i = $i + 1
        }
        exit 1
