name: Deploy OptumFA 

on:
  workflow_dispatch:

env:
  AZURE_FA_NAME: "FunctionAppDeployment2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
        
      - name: Install dependencies
        run: dotnet restore "./FunctionApps/Azure functions/FunctionAppPOCTestOptum.csproj"

      - name: Build
        run: dotnet build "./FunctionApps/Azure functions/FunctionAppPOCTestOptum.csproj" --configuration Release --no-restore

      - name: Publish
        run: dotnet publish "./FunctionApps/Azure functions/FunctionAppPOCTestOptum.csproj" --configuration Release --output ./publish

      - name: Deploy to Azure Web App
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FA_NAME }}
          publish-profile: ${{ secrets.AZURE_FA_PUBLISH_PROFILE }}
          package: ./publish
