name: Deploy Azure Function App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    # Login to Azure using a service principal
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Deploy the ARM template to create the Function App infrastructure
    - name: 'Deploy ARM template'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: 'DynamicsDeployments-eastus'
        template: 'FunctionApps/dev-fa-optum-createpackagezipfile/template.json'
        parameters: 'FunctionApps/dev-fa-optum-createpackagezipfile/parameters.json'

    # Deploy the Function App code using Azure Functions Core Tools
    - name: 'Deploy Function App'
      run: |
        func azure functionapp publish 'dev-fa-optum-createpackagezipfile-haseeb'
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_RESOURCE_GROUP: 'DynamicsDeployments-eastus'
        AZURE_FUNCTIONAPP_NAME: 'dev-fa-optum-createpackagezipfile-haseeb'
