name: Build & Deploy
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'FunctionApps/Azure functions'
  DOTNET_VERSION: 8.0.x
  OUTPUT_PATH: ${{ github.workspace }}/.output

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Publish Functions
      run: |
        cd ./FunctionApps/Azure functions  # Adjust this path as needed
        dotnet publish FunctionAppPOCTestOptum.csproj --configuration Release --output ${{ env.OUTPUT_PATH }}

    - name: Package Functions
      uses: actions/upload-artifact@v1
      with:
        name: functions
        path: ${{ env.OUTPUT_PATH }}
